### ISSUE TITLE
No way to drop traces in Java

### ISSUE THREAD

**Issue by teleological** [signalfx/signalfx-java-tracing#124]
SignalFX's tracing library for Java, unlike those for Ruby and Python, doesn't appear to provide a way to exclude traces from being forwarded. The Ruby and Python libraries, by comparison, make use of Jaeger clients which use the OpenTracing `sampling.priority` tag to determine whether to forward a trace.

The forked client in the Java library doesn't offer explicit support for `sampling.priority`, although it appears there may be server-side support for using it to force trace retention: https://docs.signalfx.com/en/latest/apm-pg/apm-pg-deployment/advanced-gateway-features.html#force-trace-retention (This feature may not be available to Ruby/Python/etc since the tag is intercepted by the client.)

On the other hand, the Java library offers some support for `manual.drop` and `manual.keep` tags, which appear as if they should enable this functionality. However, it seems that all of the configurable Samplers ignore span priority,  whether configured by their rules or by these tags, and always tell the Tracer to forward spans.

It's unclear whether the metrics property which is set according to these tags when a priority sampler is enabled (`_sampling_priority_v1`) causes traces to receive different processing once they have been received by SignalFX. I was able to confirm that `manual.drop` which sets the value for this metric to -1, does not have the effect of excluding traces from being recorded.

**Comment by teleological** [comment]
Submitted PR #125 which would enable the Rate-By-Service and Rule-Based samplers to drop traces based on priority.

**Comment by johnbley** [comment]
Hi @teleological - we will be shortly moving to the OpenTelemetry Java agent: https://github.com/open-telemetry/opentelemetry-java-instrumentation.  As such we're not expanding the feature set in this repo.  Can you look there to see if it will meet your needs?
