### ISSUE TITLE
Is Wildfly supported?

### ISSUE THREAD

**Issue by trotman23** [signalfx/signalfx-java-tracing#127]
I'd like to use this agent to instrument my Wildfly server, but I don't see explicit support for it listed in [supported software](https://github.com/signalfx/signalfx-java-tracing#requirements-and-supported-software)

The upstream datadog agent [claims to support it](https://docs.datadoghq.com/integrations/jboss_wildfly), and I even see the [wildfly smoke tests](https://github.com/signalfx/signalfx-java-tracing/tree/master/dd-smoke-tests/wildfly) are a part of this repository. 

If it isn't supported, please close this issue, but I thought I would ask. 
If it is, it would be nice to add it to the list of supported software.

**Comment by iNikem** [comment]
Supported software list consists of frameworks and libraries for which we have specific integrations. It does not list runtime environments and servers, such as Tomcat or WildFly. That should be a separate list, which is indeed absent at the moment.

And yes, this repo is expected to work with WildFly server.

**Comment by trotman23** [comment]
Thanks for the reply! I'll close this issue as my question has been answered.
