### ISSUE TITLE
Support for log4j2

### ISSUE THREAD

**Issue by kellermartin13** [signalfx/signalfx-java-tracing#129]
Your documentation states that you support log4j, but the references to the config file reference v1, which has been labeled as End of Life since 2015: https://logging.apache.org/log4j/1.2/. 

I was able to make the new log4j2 format (xml) mostly work, but I am getting all metrics except for errors. Does signal fx officially support log4j2? Or do I need to reconfigure my logging method to use something else?

Here is my adaptation of the documentation example:
```
    <Properties>
        <Property name="LOG_PATTERN">
            %d{yyyy-MM-dd HH:mm:ss.SSSZZZ} %5p ${hostName} --- [%15.15t] %-40.40c{1.} : %m %X %n%ex
        </Property>
    </Properties>
```

I attached a screenshot. I should be seeing errors show here (all of my requests are returning errors, but I am seeing a 0% error rate on the dashboard.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/30782599/95224433-aa7b6800-07c8-11eb-9eb7-b22b7767dbc9.png">

I guess my main question: do you support log4j2? If so, can the documentation be updated with this?

**Comment by johnbley** [comment]
Hi!  Sorry it's taken a while to get a response to you.  We're migrating to an OpenTelemetry-based agent, located at https://github.com/signalfx/splunk-otel-java - the documentation linked there does explicitly claim support for log4j 2 😄

**Comment by kellermartin13** [comment]
Thanks for the response - I was able to get it to work, but this is good to know. Will this project be deprecated? I see the new project is in beta.
