### ISSUE TITLE
Old version reference in jar initialisation and inside jar

### ISSUE THREAD

**Issue by sunilnagavelli** [signalfx/signalfx-java-tracing#148]
@breedx-splk , could you please check and advise me on the following issue:  When I have extracted the jar file and checked the version, it is still pointing to the old commons-io and snakeyaml version and also when the jar is getting initialized, it is showing  v0.48.0-sfx**8**, 

## commons-io and snakeyaml old versions yamls inside jar
```
$ mkdir tmp; cd tmp

$ wget https://github.com/signalfx/signalfx-java-tracing/releases/download/v0.48.0-sfx9/signalfx-tracing.jar

$ unzip signalfx-tracing.jar

$ grep -nir snakeyaml * | grep version
agent-jmxfetch.isolated/META-INF/maven/com.datadoghq/jmxfetch/pom.xml:46:  
<snakeyaml.version>1.26</snakeyaml.version>

$ grep -nir commons-io * | grep version
agent-jmxfetch.isolated/META-INF/maven/com.datadoghq/jmxfetch/pom.xml:38:  
<commons-io.version>2.4</commons-io.version>

```
these are supposed to be ```commons-io:2.11.0``` and ```snakeyaml:1.32```

## Jar Initialisation 

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/40353788/191019090-a16e015d-86d8-4752-8c61-76a645bb52d9.png">

**Comment by breedx-splk** [comment]
Hey @sunilnagavelli .

1) Yeah sorry that's probably confusing. If you look at [this part of the build script](https://github.com/signalfx/signalfx-java-tracing/blob/master/dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle#L11) you can see that we exclude the `snakeyaml` dependency from `jmxfetch` and we supply our own down on line 16. What you're seeing with those greps is what jmxfetch has declared, but we have ignored it.  

You can verify this by looking into the `pom.xml` for the version of `snakeyaml` that was actually included: 
`$ less /agent-jmxfetch.isolated/META-INF/maven/org.yaml/snakeyaml/pom.xml`

2) I forgot to update the version number, thanks for pointing that out. I will have to remake the release. I'll do that now.

**Comment by sunilnagavelli** [comment]
Great @breedx-splk, thank you for explaining that to me!!, I have verified the same now, Sure please do so🙂, and will there be a bump up in the version? Or will it be the same version 0.48.0-sfx9?, Please let me know.

**Comment by breedx-splk** [comment]
I will bump the version. I think there is less confusion that way.

**Comment by breedx-splk** [comment]
Thanks @sunilnagavelli , happy to help. Version [v0.48.0-sfx10](https://github.com/signalfx/signalfx-java-tracing/releases/tag/v0.48.0-sfx10) has been released. 

Thanks again for bringing this to our attention.
