### ISSUE TITLE
JDK12 Issue loading classes - Resolved in upstream 0.27.0

### ISSUE THREAD

**Issue by EricLemieux** [signalfx/signalfx-java-tracing#28]
Hey SFX,

I am having issues running the agent when using OpenJDK12, I believe I have traced back the issue to an issue which was resolved in the upstream.

I am unfamiliar with your update procedure, but if needed I can investigate and create a pr to update to match the upstream. 

Let me know if you need any more information.

---

Issue with bytebuddy around JDK12
https://github.com/raphw/byte-buddy/issues/631

Resolved in bytebuddy 1.9.12, which was updated in datadog 0.27.0
https://github.com/DataDog/dd-trace-java/commit/179b9b69cb2ed4587c1aacdf0a92d10b60cd4653

**Comment by rmfitzpatrick** [comment]
@EricLemieux, thank you for providing such a detailed report.  I went ahead and updated the dependency, which has been released with https://github.com/signalfx/signalfx-java-tracing/releases/tag/v0.24.0-sfx8.  Please be sure to let us know if you have any continued issues.
