### ISSUE TITLE
MDCInjectionInstrumentation displays trace_id and span_id as longs

### ISSUE THREAD

**Issue by billoneil** [signalfx/signalfx-java-tracing#68]
This is more of a UX issue than a bug but the MDCInjectionInstrumentation logs `signalfx.trace_id` and `signalfx.span_id` as longs where every reference in the signalfx UI is the HEX format.

Would it make sense to change the format to be HEX to match the UI or add an additional Instrumentation object that uses HEX instead to not break backwards compatibility? Would be happy to contribute something here would just know which direction you would like to go.

**Comment by rmfitzpatrick** [comment]
@billoneil, thank you for your suggestion and your patience!  We'll be shortly providing this change in the next release.
