### ISSUE TITLE
Spring WebFlux WebClient not instrumented

### ISSUE THREAD

**Issue by dkulig** [signalfx/signalfx-java-tracing#74]
Hi,

I am using the java-agent auto instrumentation for tracing my application. All looks good expect the thing that the underlying HTTP calls made to the downstream HTTP service doesn't seem to be traced at all. The downstream inferred service is not detected at all.

My setup: 

- Spring 5 WebFlux (reactive)
- Spring WebClient (reactive)

In order to detect the inferred service I had to do some custom instrumentation ie.

```
val span = tracer.buildSpan(downstream-service-http-request").start()
Tags.SPAN_KIND.set(span, Tags.SPAN_KIND_CLIENT)
Tags.PEER_HOSTNAME.set(span, host)
Tags.HTTP_URL.set(span, url)
Tags.HTTP_METHOD.set(span, httpMethod.name)

// do the webClient request

Tags.HTTP_STATUS.set(span, responseStatusCode)
span.finish()
```

Did I miss anything in the doc regarding the auto instrumentation of the Spring 5 WebFlux?

**Comment by rmfitzpatrick** [comment]
@dkulig thanks for your report and your patience.  Are you no longer experiencing this issue?

**Comment by dkulig** [comment]
@rmfitzpatrick Turned out I was using not the latest version of the tracing agent.
